/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
 id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
 name VARCHAR(40),
	date_of_birth DATE,
	weight_kg Decimal,
	escape_attempts INT,
	neutered BOOLEAN
);

ALTER TABLE animals ADD species VARCHAR(45);
